# Main build for @webcore/frontend-collective-react-dnd-scrollzone
# Modify major/minor/patch here for release versioning

name: $(pkgVersion)
trigger:
  branches:
    include:
      - webcore-main
  paths:
    exclude:
    - README.md
    - CHANGELOG.md

pool:
  vmImage: 'macOS-latest'

variables: 
  - group: webcore-var-group
  - name: major 
    value: 1 
  - name: minor 
    value: 0 
  - name: patch 
    value: $[counter(format('{0}.{1}', variables['major'], variables['minor']), 0)] 
  - name: pkgVersion 
    value: $[format('{0}.{1}.{2}', variables['major'], variables['minor'], variables['patch'])] 

steps:
- checkout: self
  persistCredentials: true

- bash: echo Version $(pkgVersion)

# Not fail on Std Err here because of fsevent compilation (optional) failures
- bash: yarn install

#Create .npmrc file
- bash: echo "always-auth=true" > $(System.DefaultWorkingDirectory)/.npmrc

- bash: echo "_auth=\"$(NEXUS_AUTH_SECRET)\"" >> $(System.DefaultWorkingDirectory)/.npmrc

- bash: echo "registry=https://nexus.wfmdev.com/nexus/content/groups/eamx-npm-all" >> $(System.DefaultWorkingDirectory)/.npmrc

- bash: echo "scripts-prepend-node-path=true" >> $(System.DefaultWorkingDirectory)/.npmrc
  
- bash: yarn publish --new-version $(pkgVersion)
  failOnStderr: true
